version: '3.7'
services:
    app:
        build: .
        restart: unless-stopped
        volumes:
          - .:/code
        environment:
            TZ: "Europe/Rome"
        ports:
            - 8000:8000
        tty: true
